name: pylint
on:
    pull_request:
        branches:
            - trunk
    push:
        branches:
            - trunk
jobs:
    pylint:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Setup Python 3.12
              uses: actions/setup-python@v4
              with:
                  python-version: "3.12"

            - name: Upgrade pip
              run: python -m pip install --upgrade pip

            - name: Install pylint
              run: pip install pylint

            - name: Run Linter
              run: |
                  python -m pylint . \
                    --verbose \
                    --enable-all-extensions \
                    --recursive true \
                    --disable C0103 \
                    --disable C0114 \
                    --disable C0115 \
                    --disable C0116 \
                    --disable E0401 \
                    --disable E1101 \
                    --disable R0903 \
                    --disable W0406
